# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_backup(object):
    def setupUi(self, backup):
        backup.setObjectName("backup")
        backup.resize(608, 359)
        self.tabWidget = QtWidgets.QTabWidget(backup)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 581, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_bkp_fazer = QtWidgets.QWidget()
        self.tab_bkp_fazer.setObjectName("tab_bkp_fazer")
        self.tab_bkp_progresso = QtWidgets.QProgressBar(self.tab_bkp_fazer)
        self.tab_bkp_progresso.setGeometry(QtCore.QRect(10, 172, 461, 31))
        self.tab_bkp_progresso.setProperty("value", 0)
        self.tab_bkp_progresso.setObjectName("tab_bkp_progresso")
        self.tab_bkp_btn_fazer = QtWidgets.QPushButton(self.tab_bkp_fazer)
        self.tab_bkp_btn_fazer.setGeometry(QtCore.QRect(480, 170, 89, 31))
        self.tab_bkp_btn_fazer.setObjectName("tab_bkp_btn_fazer")
        self.tab_bkp_destino = QtWidgets.QLineEdit(self.tab_bkp_fazer)
        self.tab_bkp_destino.setGeometry(QtCore.QRect(72, 10, 401, 25))
        self.tab_bkp_destino.setReadOnly(True)
        self.tab_bkp_destino.setObjectName("tab_bkp_destino")
        self.tab_bkp_destino_txt = QtWidgets.QLabel(self.tab_bkp_fazer)
        self.tab_bkp_destino_txt.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.tab_bkp_destino_txt.setObjectName("tab_bkp_destino_txt")
        self.tab_bkp_btn_selecionar = QtWidgets.QPushButton(self.tab_bkp_fazer)
        self.tab_bkp_btn_selecionar.setGeometry(QtCore.QRect(470, 10, 89, 25))
        self.tab_bkp_btn_selecionar.setObjectName("tab_bkp_btn_selecionar")
        self.tab_bkp_fzr_chrome = QtWidgets.QCheckBox(self.tab_bkp_fazer)
        self.tab_bkp_fzr_chrome.setGeometry(QtCore.QRect(10, 40, 151, 23))
        self.tab_bkp_fzr_chrome.setChecked(True)
        self.tab_bkp_fzr_chrome.setObjectName("tab_bkp_fzr_chrome")
        self.tab_bkp_fzr_imposto = QtWidgets.QCheckBox(self.tab_bkp_fazer)
        self.tab_bkp_fzr_imposto.setGeometry(QtCore.QRect(10, 80, 151, 23))
        self.tab_bkp_fzr_imposto.setChecked(True)
        self.tab_bkp_fzr_imposto.setObjectName("tab_bkp_fzr_imposto")
        self.tab_bkp_fzr_nfe = QtWidgets.QCheckBox(self.tab_bkp_fazer)
        self.tab_bkp_fzr_nfe.setGeometry(QtCore.QRect(10, 100, 151, 23))
        self.tab_bkp_fzr_nfe.setChecked(True)
        self.tab_bkp_fzr_nfe.setObjectName("tab_bkp_fzr_nfe")
        self.tab_bkp_fzr_assinatura = QtWidgets.QCheckBox(self.tab_bkp_fazer)
        self.tab_bkp_fzr_assinatura.setGeometry(QtCore.QRect(10, 120, 181, 23))
        self.tab_bkp_fzr_assinatura.setChecked(True)
        self.tab_bkp_fzr_assinatura.setObjectName("tab_bkp_fzr_assinatura")
        self.tab_bkp_fzr_chrome_2 = QtWidgets.QCheckBox(self.tab_bkp_fazer)
        self.tab_bkp_fzr_chrome_2.setGeometry(QtCore.QRect(10, 60, 151, 23))
        self.tab_bkp_fzr_chrome_2.setChecked(True)
        self.tab_bkp_fzr_chrome_2.setObjectName("tab_bkp_fzr_chrome_2")
        self.tabWidget.addTab(self.tab_bkp_fazer, "")
        self.tab_bkp_voltar = QtWidgets.QWidget()
        self.tab_bkp_voltar.setObjectName("tab_bkp_voltar")
        self.tabWidget.addTab(self.tab_bkp_voltar, "")
        self.label = QtWidgets.QLabel(backup)
        self.label.setGeometry(QtCore.QRect(10, 20, 581, 17))
        self.label.setObjectName("label")

        self.retranslateUi(backup)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(backup)

    def retranslateUi(self, backup):
        _translate = QtCore.QCoreApplication.translate
        backup.setWindowTitle(_translate("backup", "Form"))
        self.tab_bkp_btn_fazer.setText(_translate("backup", "Fazer"))
        self.tab_bkp_destino_txt.setText(_translate("backup", "Destino:"))
        self.tab_bkp_btn_selecionar.setText(_translate("backup", "Selecionar"))
        self.tab_bkp_fzr_chrome.setText(_translate("backup", "Perfil do Chrome"))
        self.tab_bkp_fzr_imposto.setText(_translate("backup", "Imposto de Renda"))
        self.tab_bkp_fzr_nfe.setText(_translate("backup", "NF-e SEBRAE"))
        self.tab_bkp_fzr_assinatura.setText(_translate("backup", "Assinatura do Outlook"))
        self.tab_bkp_fzr_chrome_2.setText(_translate("backup", "Perfil do Edge"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bkp_fazer), _translate("backup", "Fazer Backup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bkp_voltar), _translate("backup", "Voltar Backup"))
        self.label.setText(_translate("backup", "Ferramenta de Backup"))
