# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(644, 428)
        self.centralwidget = QtWidgets.QWidget(Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutMiolo = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutMiolo.setContentsMargins(0, 0, 0, 0)
        self.layoutMiolo.setObjectName("layoutMiolo")
        Janela.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Janela)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 22))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        Janela.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Janela)
        self.statusbar.setObjectName("statusbar")
        Janela.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Janela)
        self.toolBar.setObjectName("toolBar")
        Janela.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionInformacoes = QtWidgets.QAction(Janela)
        self.actionInformacoes.setObjectName("actionInformacoes")
        self.actionRede = QtWidgets.QAction(Janela)
        self.actionRede.setObjectName("actionRede")
        self.actionBackup = QtWidgets.QAction(Janela)
        self.actionBackup.setObjectName("actionBackup")
        self.actionSolucoes = QtWidgets.QAction(Janela)
        self.actionSolucoes.setObjectName("actionSolucoes")
        self.actionFechar = QtWidgets.QAction(Janela)
        self.actionFechar.setObjectName("actionFechar")
        self.menuArquivo.addAction(self.actionInformacoes)
        self.menuArquivo.addAction(self.actionRede)
        self.menuArquivo.addAction(self.actionBackup)
        self.menuArquivo.addAction(self.actionSolucoes)
        self.menuArquivo.addAction(self.actionFechar)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.toolBar.addAction(self.actionInformacoes)
        self.toolBar.addAction(self.actionRede)
        self.toolBar.addAction(self.actionBackup)
        self.toolBar.addAction(self.actionSolucoes)
        self.toolBar.addAction(self.actionFechar)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "PkTools"))
        self.menuArquivo.setTitle(_translate("Janela", "Arquivo"))
        self.toolBar.setWindowTitle(_translate("Janela", "toolBar"))
        self.actionInformacoes.setText(_translate("Janela", "Informações"))
        self.actionInformacoes.setShortcut(_translate("Janela", "Ctrl+I"))
        self.actionRede.setText(_translate("Janela", "Rede"))
        self.actionRede.setShortcut(_translate("Janela", "Ctrl+R"))
        self.actionBackup.setText(_translate("Janela", "Backup"))
        self.actionBackup.setShortcut(_translate("Janela", "Ctrl+B"))
        self.actionSolucoes.setText(_translate("Janela", "Soluções"))
        self.actionSolucoes.setShortcut(_translate("Janela", "Ctrl+S"))
        self.actionFechar.setText(_translate("Janela", "Fechar"))
